export const cropList = [
  {
    slug: 'wheat',
    emoji: '🌾',
    name: 'Wheat',
    shortName: 'Wheat',
    diseaseType: 'Fungal',
    diseases: ['Yellow Rust', 'Powdery Mildew', 'Septoria', 'Fusarium Head Blight'],
    summary: 'Detect Yellow Rust, Powdery Mildew, Septoria, and Fusarium Head Blight across tiller to grain fill.',
    headline: 'Protect grain yields from rust, mildew, and head blight.',
    accent: '#d4a838',
    image: '/assets/crop-wheat.jpg',
    products: ['stand-count', 'pest-disease', 'canopy', 'orthomosaic'],
  },
  {
    slug: 'tomato',
    emoji: '🍅',
    name: 'Tomatoes',
    shortName: 'Tomatoes',
    diseaseType: 'Fungal, Bacterial, Viral',
    diseases: ['Late Blight', 'Early Blight', 'Bacterial Spot', 'Tomato Mosaic Virus'],
    summary: 'Catch Late Blight, Early Blight, Bacterial Spot, and Tomato Mosaic Virus at the leaf level before spread.',
    headline: 'Leaf-level vigilance for processing and fresh.',
    accent: '#d95f4f',
    image: '/assets/crop-tomato.jpg',
    products: ['stand-count', 'pest-disease', 'canopy', 'orthomosaic', 'fruit-readiness'],
  },
  {
    slug: 'soybeans',
    emoji: '🫘',
    name: 'Soybeans',
    shortName: 'Soybeans',
    diseaseType: 'Fungal, Soil-borne',
    diseases: ['Soybean Rust', 'Sudden Death Syndrome (SDS)', 'Brown Stem Rot'],
    summary: 'Spot Soybean Rust, Sudden Death Syndrome (SDS), and Brown Stem Rot early to protect yield.',
    headline: 'Catch rust, SDS, and stem rot early.',
    accent: '#8d6d4c',
    image: '/assets/crop-soybeans.jpg',
    products: ['pest-disease', 'canopy', 'orthomosaic'],
  },
  {
    slug: 'cucumber',
    emoji: '🥒',
    name: 'Cucumbers',
    shortName: 'Cucumbers',
    diseaseType: 'Fungal, Bacterial',
    diseases: ['Downy Mildew', 'Anthracnose', 'Angular Leaf Spot'],
    summary: 'Identify Downy Mildew, Anthracnose, and Angular Leaf Spot across greenhouse and open fields.',
    headline: 'Protect foliage and fruit from mildew to anthracnose.',
    accent: '#438e51',
    image: '/assets/crop-cucumber.jpg',
    products: ['stand-count', 'pest-disease', 'canopy', 'orthomosaic'],
  },
  {
    slug: 'potato',
    emoji: '🥔',
    name: 'Potatoes',
    shortName: 'Potatoes',
    diseaseType: 'Fungal',
    diseases: ['Early Blight', 'Late Blight'],
    summary: 'Early detection of Early Blight and Late Blight across the foliage before tuber infection.',
    headline: 'Protect every row from early to late blight.',
    accent: '#8db54d',
    image: '/assets/crop-potato.jpg',
    products: ['stand-count', 'pest-disease', 'canopy', 'orthomosaic'],
  },
  {
    slug: 'grapevine',
    emoji: '🍇',
    name: 'Grapevines',
    shortName: 'Grapevines',
    diseaseType: 'Fungal',
    diseases: ['Powdery Mildew', 'Downy Mildew', 'Grey Spot'],
    summary: 'Monitor Powdery Mildew, Downy Mildew, and Grey Spot across vine canopies and grape clusters.',
    headline: 'Vineyard-level canopy and cluster vigilance.',
    accent: '#7a5299',
    image: '/assets/crop-grapevine.jpg',
    products: ['pest-disease', 'canopy', 'orthomosaic'],
  },
];

export const productCatalog = {
  'stand-count': {
    title: 'Stand count',
    text: 'Quantify emergence around 14 days after emergence.',
    href: '/how-it-works',
  },
  'pest-disease': {
    title: 'Pest & disease detection',
    text: 'Catch threats at the leaf level, before they spread.',
    href: '/how-it-works',
  },
  canopy: {
    title: 'Canopy coverage',
    text: 'Track vigor and closure across the whole season.',
    href: '/how-it-works',
  },
  orthomosaic: {
    title: 'Orthomosaic',
    text: 'Centimeter-accurate maps stitched from every drone flight.',
    href: '/how-it-works',
  },
  'fruit-readiness': {
    title: 'Fruit readiness',
    text: 'Predict harvest windows with ripeness mapped per plant.',
    href: '/how-it-works',
  },
};

export const plans = [
  {
    label: 'Growers',
    title: 'Field Monitoring',
    text: 'See crop risks weeks before they impact your yield.',
    pricing: 'Per hectare, billed per season',
    href: '/free-demo',
    items: [
      'Field mapping',
      'Autonomous waypoint flights',
      'Drone imagery',
      'AI pest, disease, and stress detection',
      'Severity-scored scouting reports',
      'GPS-tagged findings',
      'Canopy coverage',
      'Stand count',
      'Orthophotos and NDVI stitching',
      'Prescription maps for targeted treatment',
    ],
  },
  {
    label: 'Companies and Cooperations',
    title: 'Visibility across your entire grower network',
    text: 'Know which growers need attention before production is impacted.',
    pricing: 'Custom pricing, based on network size',
    href: '/free-demo',
    items: [
      'Multi-grower field visibility',
      'Per-field scouting reports',
      'High-resolution drone monitoring',
      'AI pest, disease, and stress detection',
      'Severity scoring across fields',
      'Geo Dashboard',
      'GPS-tagged findings',
      'Field history and trend tracking',
      'Prescription maps for targeted action',
    ],
  },
  {
    label: 'Service Providers',
    title: 'Crop Intelligence Services',
    text: 'Create a new revenue stream from the drones you already own.',
    pricing: 'Custom pricing, based on service scope',
    href: '/free-demo',
    items: [
      'Drone capture workflows',
      'Multispectral drone imagery',
      'AI scouting reports',
      'Pest, disease, and stress detection',
      'GPS-tagged findings',
      'Severity maps',
      'Prescription maps',
      'Customer-ready field reports',
      'Partner onboarding and training',
    ],
  },
  {
    label: 'Insurance',
    title: 'Digital Damage Assessment',
    text: 'Objective, drone-based field evidence for faster and more accurate assessment.',
    pricing: 'Custom pricing, based on assessment scope',
    href: '/free-demo',
    items: [
      'Drone-based field assessment',
      'Orthophoto field maps',
      'Geo-referenced evidence',
      'Damage area measurement',
      'Damage percentage estimation',
      'Severity-based documentation',
      'Before-and-after field comparison',
      'Assessment reports',
    ],
  },
];

export const features = [
  ['Pest & disease detection', 'From Colorado potato beetle to Late blight, AI identifies every threat at the leaf level before it spreads.'],
  ['Scout more on every visit', 'Cover more ground in less time and get a fuller picture of field status.'],
  ['Severity scoring', 'High, medium, and low risk ratings so you know exactly where to act first.'],
  ['New infection alerts', 'Get notified the moment fresh threats like late blight or early blight are flagged in your fields.'],
  ['Treatment guidance', 'Turn report findings into targeted spray plans and agronomy recommendations fast.'],
  ['One crop intelligence hub', 'Inspection photos, risk maps, and agronomy reports, all in one place, on any device.'],
];

export { kbCategories } from './kb-data.js';
